# A Docker Compose must always start with the version tag.
# We use '3' because it's the last version.
version: '3'

services:
  pg_db:
    container_name: postgres
    image: 'postgres:14'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  web:
    container_name: webalive
    #    restart: on-failure
    depends_on:
      - pg_db
    links:
      - pg_db
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "morbo", "./script/web_alive" ]
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
    working_dir: /usr/src/app/
  daemon:
    container_name: poold
    restart: on-failure
    depends_on:
      - web
    links:
      - web
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./script/poold" ]
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
    working_dir: /usr/src/app/
