version: "3.2"

services:

  pg_db:
    container_name: postgres
    image: "postgres:14"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  web:
    container_name: "webalive"
    image: "madcore/mojolicious"
    depends_on:
      - pg_db
    links:
      - pg_db
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "morbo", "./script/web_alive" ]
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: "$PWD"
        target: "/usr/src/app/"
    working_dir: "/usr/src/app/"

  daemon:
    container_name: "poold"
    image: "madcore/mojolicious"
    restart: on-failure
    depends_on:
      - pg_db
    links:
      - pg_db
    command: [ "./script/poold" ]
    volumes:
      - type: bind
        source: "$PWD"
        target: "/usr/src/app/"
    working_dir: "/usr/src/app/"
